sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  directories:
    - .travis/docker

before_install:
  - ./.travis/rehydrate_docker_cache.sh
  - docker-compose up -d redis rethinkdb
  - npm install

script:
  - npm run test

before_cache:
  - ./.travis/generate_docker_cache.sh
