version: "2"

services:
  redis:
    image: redis:4.0.6-alpine
    networks:
      - internal
    ports:
      - "6379:6379"

  rethinkdb:
    image: rethinkdb:2.3.6
    networks:
      - internal
    ports:
      - "9081:8080"
      - "28015:28015"
      - "29015:29015"

  nomjs-server:
    build: .
    environment:
      NODE_ENV: development
    networks:
        - internal
    ports:
      - "9080:9080"
    volumes:
      - ${PWD}/:/nomjs-server
    links:
      - redis
      - rethinkdb

networks:
  internal:
    driver: bridge
