version: '2'

services:
  redis:
    image: redis
    expose:
      - 6379

  rethinkdb:
    image: rethinkdb:2.3
    expose:
      - 28015
      - 29015

  nomjs-registry:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9080:9080
    volumes:
      - ${PWD}/:/nomjs-registry
    links:
      - redis
      - rethinkdb
